name: messio_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  intl: ^0.16.1
  flutter_bloc: ^6.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/launcher/
    - assets/fonts/
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope-regular.otf
        - asset: assets/fonts/manrope-bold.otf
          weight: 700
        - asset: assets/fonts/manrope-extrabold.otf
          weight: 800
        - asset: assets/fonts/manrope-semibold.otf
          weight: 400

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/ic_launcher.png"
  image_path_android: "assets/launcher/ic_launcher.png"
  adaptive_icon_background: "assets/launcher/ic_background.png"
  adaptive_icon_foreground: "assets/launcher/ic_foreground.png"


